import { createServerFn } from "@tanstack/react-start"
import { getRequestHeaders } from "@tanstack/react-start/server"
import { dbMiddleware } from "#/shared/middleware/db.middleware"
import { ConnectSheetSchema, DeleteSheetSchema } from "./sheets.schema"
import { auth } from "#/modules/auth/auth.utils"

// Connect a Google Sheet — saves a new SheetConnection to DB
// Extracts the sheet ID from the URL, generates a slug and API key
export const connectSheetFn = createServerFn({ method: "POST" })
  .middleware([dbMiddleware])
  .inputValidator(ConnectSheetSchema)
  .handler(async ({ context, data }) => {
    const { db } = context
    const headers = getRequestHeaders()

    // Get current logged in user from session
    const session = await auth.api.getSession({ headers })
    if (!session) throw new Error("Unauthorized")

    // Extract the sheet ID from the Google Sheets URL
    const sheetId = extractSheetId(data.sheetUrl)

    // Generate a unique slug for the public endpoint URL
    const slug = generateSlug(data.sheetName)

    // Save the sheet connection to DB
    // apiKey is auto-generated by Prisma schema default (uuid)
    return db.sheetConnection.create({
      data: {
        userId: session.user.id,
        sheetId,
        sheetName: data.sheetName,
        slug,
      },
    })
  })

// Get all sheet connections belonging to the current user
export const getMySheetsFn = createServerFn({ method: "GET" })
  .middleware([dbMiddleware])
  .handler(async ({ context }) => {
    const { db } = context
    const headers = getRequestHeaders()

    const session = await auth.api.getSession({ headers })
    if (!session) throw new Error("Unauthorized")

    // Filter by userId so each user only sees their own sheets
    return db.sheetConnection.findMany({
      where: { userId: session.user.id },
    })
  })

// Delete a sheet connection from DB
// userId check ensures users can only delete their own sheets
export const deleteSheetFn = createServerFn({ method: "POST" })
  .middleware([dbMiddleware])
  .inputValidator(DeleteSheetSchema)
  .handler(async ({ context, data }) => {
    const { db } = context
    const headers = getRequestHeaders()

    const session = await auth.api.getSession({ headers })
    if (!session) throw new Error("Unauthorized")

    return db.sheetConnection.delete({
      where: { id: data.id, userId: session.user.id },
    })
  })

// Fetch the user's 10 latest Google Sheets from Google Drive API
// Used in dashboard to show a list of sheets the user can connect
export const getUserSheetsFn = createServerFn({ method: "GET" })
  .middleware([dbMiddleware])
  .handler(async ({ context }) => {
    const { db } = context
    const headers = getRequestHeaders()

    const session = await auth.api.getSession({ headers })
    if (!session) throw new Error("Unauthorized")

    // Get the user's Google OAuth account to retrieve their access token
    const account = await db.account.findFirst({
      where: { userId: session.user.id, providerId: "google" }
    })

    if (!account?.accessToken) throw new Error("No access token found")

    // Call Google Drive API to list user's spreadsheet files
    // q: filter by Google Sheets mime type only
    // pageSize: limit to 10 results
    // orderBy: newest modified first
    // fields: only return id and name to keep response small
    const response = await fetch(
      "https://www.googleapis.com/drive/v3/files?q=mimeType='application/vnd.google-apps.spreadsheet'&pageSize=10&orderBy=modifiedTime desc&fields=files(id,name)",
      { headers: { Authorization: `Bearer ${account.accessToken}` } }
    )

    const data = await response.json()

    if (data.error) throw new Error(data.error.message)

    return data.files as { id: string; name: string }[]
  })

// Extract the Google Sheet ID from a full Google Sheets URL
// Example: https://docs.google.com/spreadsheets/d/1abc.../edit → "1abc..."
function extractSheetId(url: string): string {
  const match = url.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/)
  if (!match) throw new Error("Invalid Google Sheets URL")
  return match[1]
}

// Generate a URL-friendly slug from the sheet name
// Example: "Content Planner" → "content-planner-a1b2c3"
// Appends a random 6-character suffix to ensure uniqueness
function generateSlug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/\s+/g, "-")        // replace spaces with hyphens
      .replace(/[^a-z0-9-]/g, "") + // remove special characters
    "-" +
    crypto.randomUUID().slice(0, 6) // add random suffix for uniqueness
  )
}
